export interface Question {
    id: string | number;
    name: string;
    correctLetter: string;
    image: string;
}

export const trainingQuestions: Question[] = [
    { id: 't1', name: 'солнце', correctLetter: 'С', image: 'sun' },
    { id: 't2', name: 'компьютер', correctLetter: 'К', image: 'computer' }
];

export const testQuestions: Question[] = [
    { id: 1, name: 'книга', correctLetter: 'К', image: 'book' },
    { id: 2, name: 'яблоко', correctLetter: 'Я', image: 'apple' },
    { id: 3, name: 'дом', correctLetter: 'Д', image: 'house' },
    { id: 4, name: 'мяч', correctLetter: 'М', image: 'ball' },
    { id: 5, name: 'звезда', correctLetter: 'З', image: 'star' },
    { id: 6, name: 'кот', correctLetter: 'К', image: 'cat' },
    { id: 7, name: 'собака', correctLetter: 'С', image: 'dog' },
    { id: 8, name: 'машина', correctLetter: 'М', image: 'car' },
    { id: 9, name: 'дерево', correctLetter: 'Д', image: 'tree' },
    { id: 10, name: 'цветок', correctLetter: 'Ц', image: 'flower' },
    { id: 11, name: 'рыба', correctLetter: 'Р', image: 'fish' },
    { id: 12, name: 'птица', correctLetter: 'П', image: 'bird' },
    { id: 13, name: 'самолет', correctLetter: 'С', image: 'airplane' },
    { id: 14, name: 'корабль', correctLetter: 'К', image: 'ship' },
    { id: 15, name: 'поезд', correctLetter: 'П', image: 'train' },
    { id: 16, name: 'автобус', correctLetter: 'А', image: 'bus' },
    { id: 17, name: 'велосипед', correctLetter: 'В', image: 'bicycle' },
    { id: 18, name: 'стул', correctLetter: 'С', image: 'chair' },
    { id: 19, name: 'стол', correctLetter: 'С', image: 'table' },
    { id: 20, name: 'кровать', correctLetter: 'К', image: 'bed' },
    { id: 21, name: 'лампа', correctLetter: 'Л', image: 'lamp' },
    { id: 22, name: 'часы', correctLetter: 'Ч', image: 'clock' },
    { id: 23, name: 'телефон', correctLetter: 'Т', image: 'phone' },
    { id: 24, name: 'чашка', correctLetter: 'Ч', image: 'cup' },
    { id: 25, name: 'ложка', correctLetter: 'Л', image: 'spoon' },
    { id: 26, name: 'вилка', correctLetter: 'В', image: 'fork' },
    { id: 27, name: 'тарелка', correctLetter: 'Т', image: 'plate' },
    { id: 28, name: 'шапка', correctLetter: 'Ш', image: 'hat' },
    { id: 29, name: 'футболка', correctLetter: 'Ф', image: 'shirt' },
    { id: 30, name: 'ботинки', correctLetter: 'Б', image: 'boots' },
    { id: 31, name: 'зонт', correctLetter: 'З', image: 'umbrella' },
    { id: 32, name: 'ключ', correctLetter: 'К', image: 'key' },
    { id: 33, name: 'замок', correctLetter: 'З', image: 'lock' },
    { id: 34, name: 'карандаш', correctLetter: 'К', image: 'pencil' },
    { id: 35, name: 'рюкзак', correctLetter: 'Р', image: 'bag' },
    // Batch 1: Animals
    { id: 36, name: 'лев', correctLetter: 'Л', image: 'lion' },
    { id: 37, name: 'тигр', correctLetter: 'Т', image: 'tiger' },
    { id: 38, name: 'медведь', correctLetter: 'М', image: 'bear' },
    { id: 39, name: 'слон', correctLetter: 'С', image: 'elephant' },
    { id: 40, name: 'обезьяна', correctLetter: 'О', image: 'monkey' },
    { id: 41, name: 'жираф', correctLetter: 'Ж', image: 'giraffe' },
    { id: 42, name: 'зебра', correctLetter: 'З', image: 'zebra' },
    { id: 43, name: 'корова', correctLetter: 'К', image: 'cow' },
    { id: 44, name: 'свинья', correctLetter: 'С', image: 'pig' },
    { id: 45, name: 'овца', correctLetter: 'О', image: 'sheep' },
    // Batch 2: Animals
    { id: 46, name: 'лошадь', correctLetter: 'Л', image: 'horse' },
    { id: 47, name: 'курица', correctLetter: 'К', image: 'chicken' },
    { id: 48, name: 'утка', correctLetter: 'У', image: 'duck' },
    { id: 49, name: 'лягушка', correctLetter: 'Л', image: 'frog' },
    { id: 50, name: 'бабочка', correctLetter: 'Б', image: 'butterfly' },
    { id: 51, name: 'пчела', correctLetter: 'П', image: 'bee' },
    { id: 52, name: 'паук', correctLetter: 'П', image: 'spider' },
    { id: 53, name: 'змея', correctLetter: 'З', image: 'snake' },
    { id: 54, name: 'черепаха', correctLetter: 'Ч', image: 'turtle' },
    { id: 55, name: 'кролик', correctLetter: 'К', image: 'rabbit' },
    // Batch 3: Food
    { id: 56, name: 'банан', correctLetter: 'Б', image: 'banana' },
    { id: 57, name: 'апельсин', correctLetter: 'А', image: 'orange' },
    { id: 58, name: 'груша', correctLetter: 'Г', image: 'pear' },
    { id: 59, name: 'виноград', correctLetter: 'В', image: 'grapes' },
    { id: 60, name: 'клубника', correctLetter: 'К', image: 'strawberry' },
    { id: 61, name: 'арбуз', correctLetter: 'А', image: 'watermelon' },
    { id: 62, name: 'лимон', correctLetter: 'Л', image: 'lemon' },
    { id: 63, name: 'морковь', correctLetter: 'М', image: 'carrot' },
    { id: 64, name: 'помидор', correctLetter: 'П', image: 'tomato' },
    { id: 65, name: 'картофель', correctLetter: 'К', image: 'potato' },
    // Batch 4: Food
    { id: 66, name: 'огурец', correctLetter: 'О', image: 'cucumber' },
    { id: 67, name: 'хлеб', correctLetter: 'Х', image: 'bread' },
    { id: 68, name: 'сыр', correctLetter: 'С', image: 'cheese' },
    { id: 69, name: 'яйцо', correctLetter: 'Я', image: 'egg' },
    { id: 70, name: 'молоко', correctLetter: 'М', image: 'milk' },
    { id: 71, name: 'сок', correctLetter: 'С', image: 'juice' },
    { id: 72, name: 'мороженое', correctLetter: 'М', image: 'ice_cream' },
    { id: 73, name: 'торт', correctLetter: 'Т', image: 'cake' },
    { id: 74, name: 'пицца', correctLetter: 'П', image: 'pizza' },
    { id: 75, name: 'бургер', correctLetter: 'Б', image: 'burger' },
    // Batch 5: Clothing
    { id: 76, name: 'футболка', correctLetter: 'Ф', image: 'tshirt' },
    { id: 77, name: 'платье', correctLetter: 'П', image: 'dress' },
    { id: 78, name: 'брюки', correctLetter: 'Б', image: 'pants' },
    { id: 79, name: 'шорты', correctLetter: 'Ш', image: 'shorts' },
    { id: 80, name: 'юбка', correctLetter: 'Ю', image: 'skirt' },
    { id: 81, name: 'куртка', correctLetter: 'К', image: 'jacket' },
    { id: 82, name: 'шарф', correctLetter: 'Ш', image: 'scarf' },
    { id: 83, name: 'перчатки', correctLetter: 'П', image: 'gloves' },
    { id: 84, name: 'очки', correctLetter: 'О', image: 'glasses' },
    { id: 85, name: 'рюкзак', correctLetter: 'Р', image: 'backpack' },
    // Batch 6: Home
    { id: 86, name: 'лампа', correctLetter: 'Л', image: 'lamp' },
    { id: 87, name: 'диван', correctLetter: 'Д', image: 'sofa' },
    { id: 88, name: 'телевизор', correctLetter: 'Т', image: 'television' },
    { id: 89, name: 'унитаз', correctLetter: 'У', image: 'toilet' },
    { id: 90, name: 'раковина', correctLetter: 'Р', image: 'sink' },
    { id: 91, name: 'ванна', correctLetter: 'В', image: 'bathtub' },
    { id: 92, name: 'окно', correctLetter: 'О', image: 'window' },
    { id: 93, name: 'дверь', correctLetter: 'Д', image: 'door' },
    { id: 94, name: 'подушка', correctLetter: 'П', image: 'pillow' },
    { id: 95, name: 'одеяло', correctLetter: 'О', image: 'blanket' },
    // Batch 7: Nature & Misc
    { id: 96, name: 'луна', correctLetter: 'Л', image: 'moon' },
    { id: 97, name: 'облако', correctLetter: 'О', image: 'cloud' },
    { id: 98, name: 'дождь', correctLetter: 'Д', image: 'rain' },
    { id: 99, name: 'снеговик', correctLetter: 'С', image: 'snowman' },
    { id: 100, name: 'гора', correctLetter: 'Г', image: 'mountain' },
    { id: 101, name: 'гриб', correctLetter: 'Г', image: 'mushroom' },
    { id: 102, name: 'камень', correctLetter: 'К', image: 'stone' },
    { id: 103, name: 'ведро', correctLetter: 'В', image: 'bucket' },
    { id: 104, name: 'лопата', correctLetter: 'Л', image: 'shovel' },
    { id: 105, name: 'воздушный змей', correctLetter: 'В', image: 'kite' }
];

export const getImagePath = (name: string) => `/vocabulary/${name}.png`;
